[package]
name = "EliteAssist"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
serde_json = "1.0.140"
iced = { version = "0.13.1", features = ["svg"] }
tokio-stream = "0.1.17"
thousands = "0.2.0"
once_cell = "1.21.1"