name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Release
        run: cargo build --release --verbose

      - name: Test
        run: cargo test --verbose

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: target/release/*

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: beta
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: target/release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/*
          prerelease: true
          generate_release_notes: true
          tag_name: ${{ github.run_number }}