name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: beta

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Release
        run: cargo build --release --verbose

      - name: Test
        run: cargo test --verbose

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/*
          prerelease: true
          generate_release_notes: true